# -*- coding: utf-8 -*-
"""Iris flower classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnETjl9vNIsA9h4iPvvrsxF8q_Db4BMQ
"""

import pandas as pd

"""# **Dataset**"""

df=pd.read_csv('Iris.csv')
df

df.columns

df.head(10)

df.describe()

"""# **Checking** **null** **values****



"""

df.isnull().sum()

df.Species.value_counts()

df.info()

"""# **Data Visualization**"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 8))
sns.set(style="ticks", color_codes=True)
sns.pairplot(df, hue='Species', palette='husl', markers=["o", "s", "D"])
plt.show()

plt.figure(figsize=(10,7));
sns.scatterplot(x=df.SepalLengthCm,y=df.SepalWidthCm,hue=df.Species).set_title("Sepal length and Sepal width distribution of three flowers");

"""**Creating classify models**"""

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df['Species'] = lb_make.fit_transform(df['Species'])
df.sample(3)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

X = df.drop('Species',axis = 1)
y = df.Species

"""# **KNN** **Model**"""

from sklearn.model_selection import KFold,train_test_split,cross_val_score
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

"""# **Accuracy** **score**


"""

from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))